// Generated by CoffeeScript 2.4.1
(function() {
  var BrowserWindow, app, hello;

  ({app, BrowserWindow} = require('electron'));

  ({hello} = require('./utils'));

  app.on('ready', function() {
    var win;
    win = new BrowserWindow({
      width: 800,
      height: 800,
      webPreferences: {
        nodeIntegration: true
      }
    });
    win.loadFile('index.html');
    win.webContents.openDevTools();
    hello();
    return win.on('closed', function() {
      return win = null;
    });
  });

  app.on('window-all-closed', function() {
    return app.quit();
  });

}).call(this);
