// Generated by CoffeeScript 2.4.1
(function() {
  var app, window;

  ({app} = require('electron'));

  window = require('./window');

  app.on('ready', function() {
    return window.create();
  });

  app.on('window-all-closed', function() {
    if (process.platform !== "darwin") {
      return app.quit();
    }
  });

  app.on('activate', function() {
    return window.create();
  });

}).call(this);
