// Generated by CoffeeScript 2.4.1
(function() {
  var BrowserWindow, win;

  ({BrowserWindow} = require('electron'));

  win = null;

  module.exports = {
    create: function() {
      if (win != null) {
        return;
      }
      win = new BrowserWindow({
        width: 800,
        height: 800,
        webPreferences: {
          nodeIntegration: true
        }
      });
      win.loadFile('index.html');
      win.webContents.openDevTools();
      win.on('closed', function() {
        return win = null;
      });
      return win;
    }
  };

}).call(this);
